name: HwameiStor pr

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: unit-test
        run: make unit-test
  pull_request-e2e-test:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set env
        run: |
          echo "PROJECT_SOURCE_CODE_DIR=`echo ${GITHUB_WORKSPACE}`" >> $GITHUB_ENV
      - name: release
        run: |
          PROJECT_SOURCE_CODE_DIR=${PROJECT_SOURCE_CODE_DIR} IMAGE_REGISTRY=10.6.170.180/hwamei-e2e RELEASE_TAG=test make release
      - name: e2e-test
        env:
          E2E_TESTING_LEVEL: "pr"
        run: make e2e-test
